services:
  db:
    build:
      context: ./sql-server
      dockerfile: Dockerfile
    image: sql-express:latest
    environment:
      - SA_PASSWORD=P@ssw0rd
    ports:
      - "1433:1433"
  
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: dotnetnuke:8.0.4
    ports:
      - "8000:8000"
    depends_on:
      - db